import 'package:hive/hive.dart';

part 'user.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0) // Unique ID for this type
class User extends HiveObject {
  @HiveField(0)
  final String name;

  @HiveField(1)
  final String email;

  User(this.name, this.email);
}
